name: Build EXE

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
        pip install wxPython==4.1.1

    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed texttobat.py

    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: exe
        path: dist/texttobat.exe
